# Generated by Django 4.1 on 2022-09-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre de la Aerolinea')),
                ('concesion', models.CharField(max_length=30, verbose_name='Concesion')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aeropuertoOrigen', models.CharField(max_length=30, verbose_name='Nombre del aeropueerto de origen')),
                ('aeropuertoDestino', models.CharField(max_length=30, verbose_name='Nombre del aeropueerto de destino')),
                ('telefono', models.CharField(max_length=20, verbose_name='Ingrese el numero de Telefono')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArea', models.CharField(max_length=50, verbose_name='Area de Trabajo')),
                ('claveArea', models.CharField(max_length=10, verbose_name='Clave de area')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAsiento', models.SmallIntegerField(verbose_name='Numero de aseinto')),
                ('disponible', models.CharField(max_length=20, verbose_name='Disnponibilidad del asiento')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad del Avion')),
                ('modelo', models.CharField(max_length=10, verbose_name='Modelo del Avion')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matricula')),
                ('fabricante', models.CharField(max_length=25, verbose_name='Fabricante')),
                ('horasVuelo', models.TimeField(verbose_name='Horas de Vuelo')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroAsiento', models.CharField(max_length=10, verbose_name='Ingrese el numero de Asiento asignado')),
                ('horaCompra', models.TimeField(auto_now_add=True)),
                ('clase', models.TimeField(max_length=10, verbose_name='Ingrese el tipo de clase del boleto')),
                ('fechaSalida', models.DateField(verbose_name='Ingrese la fecha de salida del Viaje')),
                ('horaSalida', models.TimeField(verbose_name='Ingrese la hora de salida del viaje')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre de la ciudad')),
                ('cp', models.CharField(max_length=10, verbose_name='codigo postal')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50, verbose_name='Nonbre dela calle')),
                ('numeroInterior', models.CharField(max_length=4, verbose_name='numero interior')),
                ('numeroExterior', models.CharField(max_length=4, verbose_name='numero exterior')),
                ('cp', models.CharField(max_length=10, verbose_name='Codigo postal')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(max_length=40, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=40, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=9, verbose_name='Seleccione el sexo del Empleado')),
                ('clavePasaporte', models.CharField(max_length=20, verbose_name='Ingrese la clave del pasaporte')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstado', models.CharField(max_length=80, verbose_name='Nombre del estado')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(max_length=30, verbose_name='tipo de pago')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad a pagar')),
                ('nombreTitular', models.CharField(max_length=80, verbose_name='Nombre del titular')),
                ('referenciaPago', models.CharField(max_length=30, verbose_name='Referencia de pago')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePasajero', models.CharField(max_length=80, verbose_name='Nombre del pasajero')),
                ('apellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('telefono', models.CharField(max_length=13, verbose_name='Telefono del pasajero')),
                ('clavePasaporte', models.CharField(max_length=20, verbose_name='Clave de pasaporte')),
                ('sexo', models.CharField(max_length=15, verbose_name='Sexo del pasajero')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservacionViajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReservacion', models.DateTimeField(auto_now_add=True)),
                ('lugaresReservados', models.CharField(max_length=4, verbose_name='Numero de lugar')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=80, verbose_name='status de la ruta')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo tarifa')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoViaje', models.CharField(max_length=50, verbose_name='Ingrese el codigo de su viaje')),
                ('fechaLlegada', models.DateField(verbose_name='Fecha de Llegada del viaje')),
                ('horaLlegada', models.TimeField(verbose_name='Hora de Legada del viaje')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
