# Generated by Django 4.1.1 on 2022-11-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avion',
            name='capacidad',
            field=models.CharField(max_length=5, verbose_name='Capacidad del Avion'),
        ),
        migrations.AlterField(
            model_name='avion',
            name='horasVuelo',
            field=models.CharField(max_length=10, verbose_name='Horas de Vuelo'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='cp',
            field=models.IntegerField(verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Femenino', max_length=10, verbose_name='Seleccione el sexo del Empleado'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='horaLlegada',
            field=models.CharField(max_length=10, verbose_name='Hora de Legada del viaje'),
        ),
    ]
