# Generated by Django 4.1.1 on 2022-11-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0005_alter_avion_capacidad_alter_avion_horasvuelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='numAsiento',
            field=models.CharField(max_length=5, verbose_name='Numero de aseinto'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='cp',
            field=models.CharField(max_length=10, verbose_name='codigo postal'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cantidad',
            field=models.CharField(max_length=10, verbose_name='Cantidad a pagar'),
        ),
        migrations.AlterField(
            model_name='reservacionviajes',
            name='fechaReservacion',
            field=models.CharField(max_length=12, verbose_name='Fecha de Reservacion DD/MM/AAAA'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='costo',
            field=models.CharField(max_length=10, verbose_name='Costo tarifa'),
        ),
    ]
