# Generated by Django 4.1.1 on 2022-12-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0006_alter_asiento_numasiento_alter_ciudad_cp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatrabajo',
            name='claveArea',
            field=models.CharField(max_length=20, verbose_name='Clave de area'),
        ),
    ]
